name: Version Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Version Guard
        uses: AABelkhiria/version-guard@v1
